---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "nestor-lopez-c"
  description: This is a Java Spring boot app with prometheus and loki integration
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'entity-id=nestor-lopez-c'
    backstage.io/kubernetes-namespace: nestor-lopez-c-monitoring
    argocd/app-name: "nestor-lopez-c"
  links:
    - url: https://nestor-lopez-c.obs-stack.eci-idp.click/api/
      title: Url Shortener App 
      icon: externalLink
spec:
  owner: students
  lifecycle: experimental
  type: service
  system: "system:default/obs-stack"
